### ISSUE TITLE
I can't forward "f"

### ISSUE THREAD

**Issue by danrobi11** [tramhao/termusic#46] opened 2022-02-23 12:43 UTC
Hi. `f` wont forward. I've tried to re-bind it to another key. Same result :/

termusic 0.6.10 (tar binary)
kitty 0.19.3

New Edit: ~~Not `f` its `h` for `Seek forward/backward 5 seconds`~~

**Comment by tramhao** [comment] 2022-02-24 02:50
Would you please let me know which backend you're using?  I test with kitty and symphonia forward works without problem.

**Comment by tramhao** [comment] 2022-02-24 04:21
I checked the related code, and found two possible cause:
1. the key you're using is bind to other stuff in kitty.
2. the track you're listening is not seekable. As I omit the error caused by seeking, so the app will not stop or prompt error message. I could change this to a prompt.

**Comment by danrobi11** [comment] 2022-02-24 06:19
> let me know which backend you're using?

Do you mean OS? If so, MXLinux 21 based debian 11 (bullseye). WM: [EXWM](https://github.com/ch11ng/exwm)

> the key you're using is bind to other stuff in kitty

Nah. I also tested with `xfce-terminal`.

> the track you're listening is not seekable

Well. none are then. Tested files: mp3 and wma

Note: Made a mistake its not `f` which thats for lyrics. I was refering to `h` to `Seek forward/backward 5 seconds`. My bad about that. Well `h` does not work and everything I've tried to re-bind to does not work.

Im ok with the fact that my files might not be seekable. But thats weird tho. Just close the issue if you dont find anything.  

Thanks for the support tho, much appreciated. And Thanks for `termusic`.

**Comment by tramhao** [comment] 2022-02-24 07:43
with default configuration, f key is for seeking forward in a track, and `F` is for adjusting delay of lyric. By default, `h` key is used for navigation left like in vim. Maybe you have conflict key configuration inside termusic? Please check with key editor `K`.

**Comment by danrobi11** [comment] 2022-02-24 10:51
I might have changed the keybind. Regardless the bind still the function im trying to get to work is `Seek forward/backward 5 seconds`. Is the file should be able to forward if it does backward?

**Comment by tramhao** [comment] 2022-02-25 02:45
Yes, if backward works, forward should work too. You can rename your configuration in ~/.config/termusic/config.toml to other name, and it'll be rewritten with default values, and see if `f` works. It should be related to keybindings only, as other code are the same for seek forward and backward. Thanks.

**Comment by danrobi11** [comment] 2022-02-25 10:05
> You can rename your configuration in ~/.config/termusic/config.toml to other name, and it'll be rewritten with default values, and see if f works

Does not work here. Same result.

**Comment by danrobi11** [comment] 2022-02-25 11:17
Well at this point I guess I have to assume that I might have dependencies issue? 

Also, the `playing` section does not display info as intended. No time played nor progress bar:
![termusic-forward-issue](https://user-images.githubusercontent.com/48020114/155706044-454a4bc7-1006-4794-aa8d-54e34f44ddbb.png)

Should we close the issue? I've tried to compile it but my `cargo` version is too old, `termusic` wont compile with it. Your call.

**Comment by tramhao** [comment] 2022-02-26 10:50
Please keep the issue until it is fixed. Thanks.

**Comment by danrobi11** [comment] 2022-02-26 12:39
> Please keep the issue until it is fixed. Thanks.

Ok.

**Comment by tramhao** [comment] 2022-07-26 16:08
I believe it's a dependency problem. A recompile should works but some debian based distro has lower version of rust. The problem is some of my dependency is rust version 1.57.0 and up(lofty and tui-realm), thus I cannot bring down the version requirement. I'll close this issue now and if you meet any further problems, please don't hesitate to open a new one.

**Closed by tramhao** 2022-07-26 16:08 UTC
