### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by FlanOfHarmony** [tramhao/termusic#29] opened 2021-12-23 00:58 UTC
Hi, this is probably still early development but still the program looks good and works well, so well done!

Would you consider the following features? <br />
- ~~Loop only 1 song (as in VLC) mode~~
   - Already exists
- Possibily to remap shortcuts to other keys (right now, having the vim style navigation with a keyboard that looks nothing like qwerty is pretty inconvenient)
    - Now possible in latest version
- About the "Are you sure you want to quit" message box when attempting to quit the app, ~~adding <TAB> as a key to switch from "No" to "Yes" and inversely, and~~ adding the possibilty to disable this message box 
    - Now possible in latest version
- Possibilty to tune the thumbnail's size
   - Done in ver 0.6.4

**Comment by tramhao** [comment] 2021-12-23 04:30
Loop only 1 song is supported already. You can switch loop mode when focusing playlist by key `m`, and the indicator on the title will show you the meaning of loop.
keyboard remapping need some configuration change but I'll do it.
when quiting, you can use `hjkl` to switch and enter to confirm.
thumbnail size could be a configuration and I'll do it.

Thanks for the feedback and have a nice day.

**Comment by tramhao** [comment] 2021-12-24 06:43
thumbnail size and location is working in 0.6.4. Some bugs about it but you can try.

**Comment by windwp** [comment] 2021-12-28 09:28
hi i try  termusic and it is very good.
can you make a mode when it hide a library and zoom a lyric window?
 how do i save a lyric download by tag editor. 
I press t to goto tag editor and press enter then `l` to see a lyric but i don't know how to save a lyric to that song.
Thank

**Comment by tramhao** [comment] 2021-12-29 03:39
About hide a library and zoom a lyric window, let me think about it. 
About saving the lyric, it's a bug in master branch. I'll fix it today. After you press l key, the lyric should be saved to the song automatically.

**Comment by tramhao** [comment] 2021-12-29 04:20
I just checked that saving lyric is all right in v0.6.4, please checkout this version. Meanwhile, I'm still discussing this issue with the author of lofty-rs. Thanks.

**Comment by tramhao** [comment] 2021-12-29 15:00
For the lyric problem, I switch back to old implementation for mp3 file and should fix the problem in master.

**Comment by windwp** [comment] 2021-12-29 23:29
thank it working @tramhao

**Comment by FlanOfHarmony** [comment] 2021-12-30 15:24
> thumbnail size and location is working in 0.6.4. Some bugs about it but you can try.

Yep it seems to be working alright, just visual bugs when width is too big but I guess those are the bugs you mention. However and I don't know if you noticed, the thumbnail can overlap with the tag editing window when next song gets played/song gets replayed. By the way, in tag editing mode, `shift+Tab` to go back the "switch focus" seems logical and not too hard to implement.

Finally, I think it could be great to have a toggle in the tag editing mode to manually edit `Album`, `Song Name`, `Track Number`, ... but it's a relatively big and not too necessary feature and I guess there are more urgent things to do. Perhaps if you run out of ideas in the future ? :-)

**Comment by tramhao** [comment] 2021-12-31 05:51
About the size of thumbnail, I've updated related code in dev branch to show error messages when it's too big, and also use relative values to adapt to different size of windows. Will be released in 0.6.5. 
Shift+Tab should be ok to implement for tag editor and color editor. 
And for song name and artist name, it can be edited manually then confirmed by rename. For other information, I don't know which fields are most used but if we need a good way to edit it, maybe the best way is to separate it from tag download. Any ideas are welcome and have a nice holiday!

**Comment by tramhao** [comment] 2021-12-31 08:24
I update the dev branch to remap some keys. The problem is that I just enabled vim keys and don't know which keys might be conflicting your keyboard layout. What's your keyboard layout? What keys are generally used for navigation in your layout? You can checkout dev branch to try the remap.

**Comment by tramhao** [comment] 2021-12-31 08:26
> > thumbnail size and location is working in 0.6.4. Some bugs about it but you can try.
> 
> Yep it seems to be working alright, just visual bugs when width is too big but I guess those are the bugs you mention. However and I don't know if you noticed, the thumbnail can overlap with the tag editing window when next song gets played/song gets replayed. By the way, in tag editing mode, `shift+Tab` to go back the "switch focus" seems logical and not too hard to implement.
> 
> Finally, I think it could be great to have a toggle in the tag editing mode to manually edit `Album`, `Song Name`, `Track Number`, ... but it's a relatively big and not too necessary feature and I guess there are more urgent things to do. Perhaps if you run out of ideas in the future ? :-)

Shit tab works in dev branch now.

**Comment by FlanOfHarmony** [comment] 2022-01-01 20:59
>About the size of thumbnail, I've updated related code in dev 
The behavior is still kind of odd but yeah it seems to work. What bugs me is that relative values are not between the right-down corner of the picture and the right down corner of the `Playlist` Box.
 >And for song name and artist name, it can be edited manually then confirmed by rename.
 Oops my bad, didn't realize that. 
 >For other information, I don't know which fields are most used
 Well I think that `Artist`, `Album` and `Track number` are the most used, but if you consider switching to another menu some other fields could be `Genre` or `Date` (amongst others)  but (I think) they are far less used.
 >don't know which keys might be conflicting your keyboard layout. What's your keyboard layout? What keys are generally used for navigation in your layout?
I'm using the equivalent of the dvorak layout, but for my own native language, and there are indeed conflincting keys (I just tested dev branch). I don't think there are any solutions other than to add the possibility to remap every key...
Have a nice holiday too!

**Comment by tramhao** [comment] 2022-01-03 15:48
> > About the size of thumbnail, I've updated related code in dev
> 
> The behavior is still kind of odd but yeah it seems to work. What bugs me is that relative values are not between the right-down corner of the picture and the right down corner of the `Playlist` Box.
> 
> > And for song name and artist name, it can be edited manually then confirmed by rename.
> 
> Oops my bad, didn't realize that.
> 
> > For other information, I don't know which fields are most used
> 
> Well I think that `Artist`, `Album` and `Track number` are the most used, but if you consider switching to another menu some other fields could be `Genre` or `Date` (amongst others) but (I think) they are far less used.
> 
> > don't know which keys might be conflicting your keyboard layout. What's your keyboard layout? What keys are generally used for navigation in your layout?
> 
> I'm using the equivalent of the dvorak layout, but for my own native language, and there are indeed conflincting keys (I just tested dev branch). I don't think there are any solutions other than to add the possibility to remap every key... Have a nice holiday too!

About the position of the album box, it's not very accurate. As in terminal, the value is by row and column. I test in kitty, and the size is more fixed. In alacritty(when using ueberzug), the vertical position could be 1 line wrong. I have no clue what to do about ueberzug at this moment.

**Closed** 2022-02-28 22:02 UTC
